services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: idkwhyureadthis
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: prac-project

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U idkwhyureadthis -d prac-project"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  db-service:
    build: backend/db-service/
    environment:
      PORT: 8081
      CONN_URL: postgresql://idkwhyureadthis:12345@db:5432/prac-project
      ADMIN_NAME: admin
      ADMIN_PASSWORD: 12345
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy
    links:
      - db


  frontend:
    build: frontend/
    ports:
      - "5173:5173"

  auth-service:
    build: backend/auth-service/
    environment:
      PORT: 8080
      SECRET_KEY: mtuci_market_asdasd
    ports:
      - "8080:8080"

  api:
    build: backend/api/
    ports:
      - "8082:8082"
    environment:
      PORT: 8082


volumes:
  postgres_data: